name: Push to Trigger

on:
  push:
    branches:
      - main

jobs:
  trigger-b:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Action
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.HJ_TOKEN }}" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/iamxiaojianzheng/hexo-jiahe/actions/workflows/main.yml/dispatches
